# Generated by Django 2.0.5 on 2018-10-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined_nsbe',
            field=models.CharField(max_length=25, null=True, verbose_name='Date Joined NSBE?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dues_paid',
            field=models.BooleanField(default=False, verbose_name='Dues Paid?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='eboard_member',
            field=models.BooleanField(default=False, verbose_name='E-Board Member?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=45, unique=True, verbose_name='Name'),
        ),
    ]
