# Generated by Django 2.0.5 on 2018-10-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181009_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='classification',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('FR', 'Senior')], default='FR', max_length=2),
        ),
    ]
