# Generated by Django 2.0.5 on 2018-10-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade_point_average',
            field=models.CharField(default=0, max_length=4, verbose_name='GPA'),
        ),
    ]
